version: '3.9'

services:
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: dbpassword
            MYSQL_DATABASE: wordpress_local
            MYSQL_USER: wordpress_db_user
            MYSQL_PASSWORD: wordpress_db_password
        platform: linux/x86_64

    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        volumes:
            - wordpress_data:/var/www/html
            - ./plugins:/var/www/html/wp-content/plugins
        ports:
            - '8000:80'
        restart: always
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wordpress_db_user
            WORDPRESS_DB_PASSWORD: wordpress_db_password
            WORDPRESS_DB_NAME: wordpress_local
            WORDPRESS_ENVIRONMENT: development

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '8001:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: dbpassword

volumes:
    db_data: {}
    wordpress_data: {}
